require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4

  TargetRailsVersion: 8.1

  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "config/environments/*"
    - "config/initializers/*"
    - "lib/tasks/*"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Performance/TimesMap:
  Enabled: true

Rails/FindById:
  EnforcedStyle: find_by

Rails/HttpPositionalArguments:
  EnforcedStyle: keywords

Rails/HelperInstanceVariable:
  Enabled: true
